---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Shared Homepage"
subtitle: "Dura IT Ops"
logo: "assets/duralogo.png"
# icon: "fas fa-skull-crossbones"

Columns: "4"

# Optional message
# See https://bulma.io/documentation/components/message/#colors for styling options.
#message:
  #style: "is-warning"
  #title: "Hi there!"
  #content: "Welcome to the new IT OPS Dashboard! Please let Jason know if anything needs changing."

# Optional navbar
links:
  - name: "Dura"
    icon: "fas fa-home"
    url: "https://jstewds.github.io/"
  - name: "Bertch"
    icon: "fas fa-road"
    url: "https://jstewds.github.io/bertch/"
  - name: "Office 365"
    icon: "fas fa-cogs"
    url: "https://jstewds.github.io/o365/"
  - name: "Azure AD (AAD)"
    icon: "fas fa-book"
    url: "https://portal.azure.com/#home"
  - name: "DuraLINK"
    icon: "fas fa-link"
    url: "https://duralink.durasupreme.com"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Monitoring"
    icon: "fas fa-heartbeat"
    items:
      - name: "PRTG"
        logo: "/assets/tools/PRTG.png"
        subtitle: "Network and Server Monitor"
        tag: "Wacky Germans!"
        url: "https://hawk.durasupreme.com"
      - name: "NetDisco"
        logo: "/assets/tools/disco.jpg"
        subtitle: "Network stats and config changes"
        tag: "Boogie Wonderland!"
        url: "http://192.168.1.61:5000/"
      - name: "LANSweeper"
        logo: "/assets/tools/lansweeper.png"
        subtitle: "Workstation and Server Inventory Tool"
        tag: "BringOnTheBroom"
        url: "http://owl.durasupreme.com:81"
      - name: "CommVault"
        logo: "/assets/tools/commvault.png"
        subtitle: "Backups"
        tag: "savor the flavor"
        url: "https://butternut.durasupreme.com/adminconsole/"
      - name: "PagerDuty"
        logo: "/assets/tools/pagerduty.png"
        subtitle: "On-Call Alerting System"
        tag: "Who took my false teeth?!"
        url: "https://durasupreme.pagerduty.com"
      - name: "Proteus"
        logo: "/assets/tools/proteus.png"
        subtitle: "Sever Room Environmental Monitoring"
        tag: "Blizzards are delicious"
        url: "https://cloud.proteussensor.com/html/index.php"
      - name: "Meraki"
        logo: "/assets/tools/meraki.png"
        subtitle: "All APs, Pierz Meraki Switch & Security"
        tag: "I'm a little teapot"
        url: "https://n151.meraki.com/Pierz-switch/n/m2llRdxc/manage/usage/list"
      - name: "Unimus"
        logo: "/assets/tools/unimus.png"
        subtitle: "Switch Config Backup Utility"
        tag: "Sudo? No, You do!"
        url: "http://owl.durasupreme.com:8085/"
  - name: "SaaS Apps"
    icon: "fas fa-cloud-upload-alt"
    items:
      - name: "SharePoint - SCB IT"
        logo: "/assets/tools/sharepoint.png"
        subtitle: "All of the things"
        tag: "Sharing IS caring"
        url: "https://durasupremeinc.sharepoint.com/sites/SupremeCabinetry/Information%20Technology"
      - name: "IT Glue"
        logo: "/assets/tools/itglue.png"
        subtitle: "Documentation"
        tag: "TastesGreat"
        url: "https://durasupreme.itglue.com/3571316"
      - name: "FreshService"
        logo: "/assets/tools/freshservice.png"
        subtitle: "Our Ticketing System"
        tag: "No ticket? No work."
        url: "https://durasupreme.freshservice.com/helpdesk/tickets"
      - name: "SmartSheet"
        logo: "/assets/tools/smartsheet.png"
        subtitle: "Project Management"
        tag: "WhoNeedsExcel?"
        url: "https://app.smartsheet.com"
      - name: "CloudFlare"
        logo: "/assets/tools/cloudflare.png"
        subtitle: "External DNS"
        tag: "It's always DNS"
        url: "https://dash.cloudflare.com/login"
      - name: "CrowdStrike"
        logo: "/assets/tools/crowdstrike.png"
        subtitle: "Security Software"
        tag: "I was saying boo-urns!"
        url: "https://falcon.crowdstrike.com"
      - name: "Securence"
        logo: "/assets/tools/securence.png"
        subtitle: "Spam Filtering Software"
        tag: "It's SPAMTASTC!"
        url: "https://admin.securence.com/index.php"
      - name: "Metro Alarm Virtual Keypad"
        logo: "/assets/tools/virtualkeypad.png"
        subtitle: "Remote Access to Security"
        tag: "Beep-boop-bop!"
        url: "https://www.virtualkeypad.com/"
      - name: "GoDaddy"
        logo: "/assets/tools/godaddy.png"
        subtitle: "Manage SSL Certs"
        tag: "SSL = Super Soaker Land"
        url: "https://account.godaddy.com/products"
  - name: "Other Tools"
    icon: "fas fa-map-signs"
    items:
      - name: "URLScan"
        logo: "/assets/tools/urlscan.png"
        subtitle: "Scan a URL to see if it is malicious"
        tag: "SurfSafely"
        url: "https://urlscan.io/"
      - name: "AnyRun"
        logo: "/assets/tools/anyrun.png"
        subtitle: "Scan a file to see if it is malicious"
        tag: "ThanksStranger!"
        url: "https://app.any.run/"
      - name: "Hybrid Analysis"
        logo: "/assets/tools/hybrid.png"
        subtitle: "Scan a file to see if it is malicious"
        tag: "It is not a Prius"
        url: "https://www.hybrid-analysis.com/"
      - name: "DNSlytics"
        logo: "/assets/tools/dnslytics.png"
        subtitle: "Full DNS records, etc."
        tag: "It's always DNS"
        url: "https://dnslytics.com/"
      - name: "MXToolbox"
        logo: "/assets/tools/mxtoolbox.png"
        subtitle: "MX Records, Email Blacklists, etc."
        tag: "You've got mail!"
        url: "https://mxtoolbox.com/"
       