---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Shared Homepage"
subtitle: "Dura IT Ops"
logo: "assets/logo.png"
# icon: "fas fa-skull-crossbones"

# Optional message
# See https://bulma.io/documentation/components/message/#colors for styling options.
message:
  style: "is-warning"
  title: "Hi there!"
  content: "Welcome to the new IT OPS Dashboard! Please let Jason know if anything needs changing."

# Optional navbar
links:
  - name: "ansible"
    icon: "fab fa-github"
    url: "https://github.com/xxxxx/ansible/"
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://wiki.xxxxxx.com/"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Monitoring"
    icon: "fas fa-heartbeat"
    items:
      - name: "PRTG"
        logo: "/assets/tools/monit.png"
        subtitle: "Network and Server Monitor"
        tag: "PRTG"
        url: "https://hawk.durasupreme.com"
      - name: "LANSweeper"
        logo: "/assets/tools/grafana.png"
        subtitle: "Workstation and Server Inventory Tool"
        # Optional tagstyle
        # Same styling options as the optional message.
        #tagstyle: "is-success"
        url: "http://owl.durasupreme.com:81"