---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Shared Homepage"
subtitle: "Dura IT Ops"
logo: "assets/duralogo.png"
# icon: "fas fa-skull-crossbones"

# Optional message
# See https://bulma.io/documentation/components/message/#colors for styling options.
#message:
  #style: "is-warning"
  #title: "Hi there!"
  #content: "Welcome to the new IT OPS Dashboard! Please let Jason know if anything needs changing."

# Optional navbar
links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Monitoring"
    icon: "fas fa-heartbeat"
    items:
      - name: "PRTG"
        logo: "/assets/tools/PRTG.png"
        subtitle: "Network and Server Monitor"
        tag: "Wacky Germans!"
        url: "https://hawk.durasupreme.com"
      - name: "LANSweeper"
        logo: "/assets/tools/lansweeper.png"
        subtitle: "Workstation and Server Inventory Tool"
        tag: "BringOnTheBroom"
        # Optional tagstyle
        # Same styling options as the optional message.
        #tagstyle: "is-success"
        url: "http://owl.durasupreme.com:81"
      - name: "PagerDuty"
        logo: "/assets/tools/pagerduty.png"
        subtitle: "On-Call Alerting System"
        tag: "Who took my false teeth?!"
        url: "https://durasupreme.pagerduty.com"
  - name: "SaaS Apps"
    icon: "fas fa-cloud-upload-alt"
    items:
      - name: "IT Glue"
        logo: "/assets/tools/itglue.png"
        subtitle: "Documentation"
        tag: "TastesGreat"
        url: "https://durasupreme.itglue.com"
      - name: "FreshService"
        logo: "/assets/tools/freshservice.png"
        subtitle: "Our Ticketing System"
        tag: "No ticket? No work."
        # Optional tagstyle
        # Same styling options as the optional message.
        #tagstyle: "is-success"
        url: "https://durasupreme.freshservice.com/helpdesk/tickets"
      - name: "SmartSheet"
        logo: "/assets/tools/smartsheet.png"
        subtitle: "Project Management"
        tag: "WhoNeedsExcel?"
        url: "https://app.smartsheet.com"
  - name: "Other Tools"
    icon: "fas fa-map-signs"
    items:
      - name: "URLScan"
        logo: "/assets/tools/urlscan.png"
        subtitle: "Scan a URL to see if it is malicious"
        tag: "SurfSafely"
        url: "https://urlscan.io/"
      - name: "AnyRun"
        logo: "/assets/tools/anyrun.png"
        subtitle: "Scan a file to see if it is malicious"
        tag: "ThanksStranger!"
        # Optional tagstyle
        # Same styling options as the optional message.
        #tagstyle: "is-success"
        url: "https://app.any.run/"
      - name: "NeverSSL"
        logo: "/assets/tools/neverssl.png"
        subtitle: "Guest Wifi Access Trick"
        tag: "SecuritySadness"
        url: "http://neverssl.com"
