---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Shared Homepage"
subtitle: "Dura IT Ops"
logo: "assets/duralogo.png"
# icon: "fas fa-skull-crossbones"

# Optional message
# See https://bulma.io/documentation/components/message/#colors for styling options.
#message:
  #style: "is-warning"
  #title: "Hi there!"
  #content: "Welcome to the new IT OPS Dashboard! Please let Jason know if anything needs changing."

# Optional navbar
links:
  - name: "Dura"
    icon: "fab fa-github"
    url: "https://jstewds.github.io/"
  - name: "Bertch"
    icon: "fas fa-road"
    url: ""
  - name: "Office 365"
    icon: "fas fa-cogs"
    url: ""

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Monitoring"
    icon: "fas fa-heartbeat"
    items:
      - name: "PRTG"
        logo: "/assets/tools/PRTG.png"
        subtitle: "Network and Server Monitor"
        tag: "Wacky Germans!"
        url: "https://hawk.durasupreme.com"
      - name: "NetDisco"
        logo: "/assets/tools/disco.jpg"
        subtitle: "Network stats and config changes"
        tag: "Boogie Wonderland!"
        url: "http://netdisco.durasupreme.com"
      - name: "LANSweeper"
        logo: "/assets/tools/lansweeper.png"
        subtitle: "Workstation and Server Inventory Tool"
        tag: "BringOnTheBroom"
        url: "http://owl.durasupreme.com:81"
      - name: "PagerDuty"
        logo: "/assets/tools/pagerduty.png"
        subtitle: "On-Call Alerting System"
        tag: "Who took my false teeth?!"
        url: "https://durasupreme.pagerduty.com"
      - name: "Proteus"
        logo: "/assets/tools/proteus.png"
        subtitle: "Sever Room Environmental Monitoring"
        tag: "Blizzards are delicious"
        url: "https://cloud.proteussensor.com/html/index.php"
      - name: "Meraki"
        logo: "/assets/tools/meraki.png"
        subtitle: "Pierz Meraki Switch & Security"
        tag: "I'm a little teapot"
        url: "https://n151.meraki.com/Pierz-switch/n/m2llRdxc/manage/usage/list"
  - name: "SaaS Apps"
    icon: "fas fa-cloud-upload-alt"
    items:
      - name: "IT Glue"
        logo: "/assets/tools/itglue.png"
        subtitle: "Documentation"
        tag: "TastesGreat"
        url: "https://durasupreme.itglue.com"
      - name: "FreshService"
        logo: "/assets/tools/freshservice.png"
        subtitle: "Our Ticketing System"
        tag: "No ticket? No work."
        url: "https://durasupreme.freshservice.com/helpdesk/tickets"
      - name: "SmartSheet"
        logo: "/assets/tools/smartsheet.png"
        subtitle: "Project Management"
        tag: "WhoNeedsExcel?"
        url: "https://app.smartsheet.com"
      - name: "CloudFlare"
        logo: "/assets/tools/cloudflare.png"
        subtitle: "External DNS"
        tag: "It's always DNS"
        url: "https://dash.cloudflare.com/login"
      - name: "CrowdStrike"
        logo: "/assets/tools/crowdstrike.png"
        subtitle: "Security Software"
        tag: "I was saying boo-urns!"
        url: "https://falcon.crowdstrike.com"
      - name: "Securence"
        logo: "/assets/tools/securence.png"
        subtitle: "Spam Filtering Software"
        tag: "It's SPAMTASTC!"
        url: "https://admin.securence.com/index.php"
      - name: "Metro Alarm Virtual Keypad"
        logo: "/assets/tools/virtualkeypad.png"
        subtitle: "Remote Access to Security"
        tag: "Beep-boop-bop!"
        url: "https://www.virtualkeypad.com/"
      - name: "GoDaddy"
        logo: "/assets/tools/godaddy.png"
        subtitle: "Manage SSL Certs"
        tag: "SSL = Super Soaker Land"
        url: "https://account.godaddy.com/products"
  - name: "Office 365"
    icon: "fas fa-cogs"
    items:
      - name: "Office Admin Page"
        logo: "/assets/tools/o365.png"
        subtitle: "Access the Main Office 365 Admin Page"
        tag: "Admin? More like Sadmin..."
        url: "https://admin.microsoft.com/AdminPortal/Home#/homepage"
      - name: "Exchange Admin Center"
        logo: "/assets/tools/exchange.png"
        subtitle: "Direct Access to the Exchange Admin Center"
        tag: "Which witch is which?"
        url: "https://outlook.office365.com/ecp/?rfr=Admin_o365&exsvurl=1&mkt=en-US&Realm=durasupreme.com"
      - name: "Sharepoint Admin Center"
        logo: "/assets/tools/sharepoint.png"
        subtitle: "Direct Access to the Sharepoint Admin Center"
        tag: "Sharing is caring"
        url: "https://durasupremeinc-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/home"
  - name: "Other Tools"
    icon: "fas fa-map-signs"
    items:
      - name: "URLScan"
        logo: "/assets/tools/urlscan.png"
        subtitle: "Scan a URL to see if it is malicious"
        tag: "SurfSafely"
        url: "https://urlscan.io/"
      - name: "AnyRun"
        logo: "/assets/tools/anyrun.png"
        subtitle: "Scan a file to see if it is malicious"
        tag: "ThanksStranger!"
        url: "https://app.any.run/"
      - name: "Hybrid Analysis"
        logo: "/assets/tools/hybrid.png"
        subtitle: "Scan a file to see if it is malicious"
        tag: "It is not a Prius"
        url: "https://www.hybrid-analysis.com/"
